apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-back
spec:
  ingressClassName: nginx
  rules:
    - http:
        paths:
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: back-service
                port:
                  number: 8080
