apiVersion: v1
kind: Service
metadata:
  name: back-service
spec:
  type: NodePort
  selector:
    app: back
  ports:
    - protocol: TCP
      port: {{ .Values.image.port }}
      targetPort: {{ .Values.image.port }}
      nodePort: 31000
