---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: front-pdb
spec:
  minAvailable: 2
  selector:
    matchLabels:
      app: front
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: back-pdb
spec:
  minAvailable: 2
  selector:
    matchLabels:
      app: back
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: db-pdb
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: mongo
---
