architecture: "standalone"

global:
  security:
    allowInsecureImages: true

extraEnvVars:
  - name: MONGO_INITDB_ROOT_USERNAME
    valueFrom:
      secretKeyRef:
        name: mongo-secret
        key: mongo-user  
  - name: MONGO_INITDB_ROOT_PASSWORD
    valueFrom:
      secretKeyRef:
        name: mongo-secret
        key: mongo-password
image:
  repository: arm64v8/mongo
  tag: latest

persistence:
  mountPath: "/data/db"
