# Default values for front-todoapp.
# This is a YAML-formatted file.

replicaCount: 2
name: deployment-front 

image:
  repository: mafadegrande/frontgoapp
  tag: dev
  port: 3000

pdb:
  minAvailable: 2

probe:
  httpGet: "/"


service:
  port: 80
