apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.name }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: front
  template:
    metadata:
      labels:
        app: front
    spec: 
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              podAffinityTerm:
                labelSelector:
                  matchExpressions:
                  - key: app
                    operator: In
                    values:
                      - front
                topologyKey: "kubernetes.io/hostname"
      containers:
        - name: front-app
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          ports:
            - containerPort: {{ .Values.image.port }}
          livenessProbe:
            httpGet:
              path: {{ .Values.probe.httpGet }}
              port: {{ .Values.image.port }}
            initialDelaySeconds: 3
            periodSeconds: 5
          readinessProbe:
            httpGet:
              path: {{ .Values.probe.httpGet }}
              port: {{ .Values.image.port }}
            initialDelaySeconds: 3
            periodSeconds: 5

